### ISSUE TITLE
API is awkward

### ISSUE THREAD

**Issue by abersnaze** [ReactiveX/RxJavaFileUtils#1]
At the moment the API is `Map<Path, Kind[]> -> Observable<WatchEvent<?>>` and `Path -> Kind[] -> Observable<WatchEvent<?>>`.  This seem too literal of an interpretation of the underlying API.

The first problem that I have is that notification that events were dropped (`WatchEvent<Object>`) and changes (`WatchEvent<Path>`) means that the Observable has to have a wild card type. I would like to see the API have a stronger type definition.  Two ideas that i've had are:
- separate the events as two streams one of `Observable<WatchEvent<Path>>` and the other of `Observable<Void>`
- use an Either type `Observable<Either<WatchEvent<Path>,Void>>`

The second is that I'm not sure why there is a method that takes `Map<Path, Kind[]>` couldn't that be done externally as the flatMap of individual `Path -> Kind[] -> Observable<WatchEvent<Path>>`.

**Comment by robertroeser** [comment]
"The first problem that I have is that notification that events were dropped (WatchEvent<Object>) and changes (WatchEvent<Path>) means that the Observable has to have a wild card type. I would like to see the API have a stronger type definition. "
I don't want to return two different streams. That seems kind of clunky. I could change it to WatchEvent<Optional<Path>> and then when it's overflow just return an empty Optional

"The second is that I'm not sure why there is a method that takes Map<Path, Kind[]> couldn't that be done externally as the flatMap of individual Path -> Kind[] -> Observable<WatchEvent<Path>>."
Flatmapping like that would create a bunch of WatchService instances - you can register more than path to a particular watch service with difference sets of events per path you're watching.
