### ISSUE TITLE
Deployed to Maven Central?

### ISSUE THREAD

**Issue by jschneider** [ReactiveX/RxJavaFileUtils#10]
Hi guys,

I could not find anything for "rxjava-file-utils" on maven central. The documentation tells me, there should be something...
Could you double check this?

**Comment by stevegury** [comment]
@jschneider thanks for pointing this out.

We need to authorize the library synchronization between bintray and maven central, I've made the change, it will take a couple of hours/days before I can deploy to maven central.
I'll update this issue when it's done.

**Comment by stevegury** [comment]
@jschneider v0.1.4 is now available in [maven central](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22rxjava-file-utils%22)
